package com.angryzyh.mapper;

import com.angryzyh.model.Emp;
import com.angryzyh.model.EmpExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface EmpMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ssm_mybatis_employee
     *
     * @mbg.generated Thu Jul 07 16:08:11 CST 2022
     */
    long countByExample(EmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ssm_mybatis_employee
     *
     * @mbg.generated Thu Jul 07 16:08:11 CST 2022
     */
    int deleteByExample(EmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ssm_mybatis_employee
     *
     * @mbg.generated Thu Jul 07 16:08:11 CST 2022
     */
    int deleteByPrimaryKey(Integer empId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ssm_mybatis_employee
     *
     * @mbg.generated Thu Jul 07 16:08:11 CST 2022
     */
    int insert(Emp row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ssm_mybatis_employee
     *
     * @mbg.generated Thu Jul 07 16:08:11 CST 2022
     */
    int insertSelective(Emp row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ssm_mybatis_employee
     *
     * @mbg.generated Thu Jul 07 16:08:11 CST 2022
     */
    List<Emp> selectByExample(EmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ssm_mybatis_employee
     *
     * @mbg.generated Thu Jul 07 16:08:11 CST 2022
     */
    Emp selectByPrimaryKey(Integer empId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ssm_mybatis_employee
     *
     * @mbg.generated Thu Jul 07 16:08:11 CST 2022
     */
    int updateByExampleSelective(@Param("row") Emp row, @Param("example") EmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ssm_mybatis_employee
     *
     * @mbg.generated Thu Jul 07 16:08:11 CST 2022
     */
    int updateByExample(@Param("row") Emp row, @Param("example") EmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ssm_mybatis_employee
     *
     * @mbg.generated Thu Jul 07 16:08:11 CST 2022
     */
    int updateByPrimaryKeySelective(Emp row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ssm_mybatis_employee
     *
     * @mbg.generated Thu Jul 07 16:08:11 CST 2022
     */
    int updateByPrimaryKey(Emp row);
}