spring:
  boot:
    admin:
      client:
        url: http://localhost:8081

server:
  port: 80

management:
  endpoint:
    health:
      show-components: always
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true