spring:
  profiles:
    active: @profile.active@
    group:
      "dev": devDB,devRedis,devMVC,devMongoDB
      "pro": proDB,proRedis,proMVC
      "test": testDB,testRedis,testMVC
  main:
    banner-mode: off
