spring:
  profiles:
    active: @profile.active@
    group:
      "dev": devMVC,devDB,devRedis,devMongoDB,devRabbitMQ
      "pro": proDB,proRedis,proMVC
      "test": testDB,testRedis,testMVC
  main:
    banner-mode: off
