spring:
  main:
    banner-mode: off
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ssm?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: root

server:
  port: 80

mybatis-plus:
  global-config:
    banner: off
    db-config:
      table-prefix: sbmp_mybatisplus_
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
