package com.angryzyh.model;

public class Emp {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_mybatis_employee.emp_id
     *
     * @mbg.generated Thu Jul 07 16:58:50 CST 2022
     */
    private Integer empId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_mybatis_employee.emp_name
     *
     * @mbg.generated Thu Jul 07 16:58:50 CST 2022
     */
    private String empName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_mybatis_employee.emp_age
     *
     * @mbg.generated Thu Jul 07 16:58:50 CST 2022
     */
    private Integer empAge;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_mybatis_employee.emp_sex
     *
     * @mbg.generated Thu Jul 07 16:58:50 CST 2022
     */
    private String empSex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_mybatis_employee.emp_email
     *
     * @mbg.generated Thu Jul 07 16:58:50 CST 2022
     */
    private String empEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_mybatis_employee.d_id
     *
     * @mbg.generated Thu Jul 07 16:58:50 CST 2022
     */
    private Integer dId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_mybatis_employee.emp_id
     *
     * @return the value of ssm_mybatis_employee.emp_id
     *
     * @mbg.generated Thu Jul 07 16:58:50 CST 2022
     */
    public Integer getEmpId() {
        return empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_mybatis_employee.emp_id
     *
     * @param empId the value for ssm_mybatis_employee.emp_id
     *
     * @mbg.generated Thu Jul 07 16:58:50 CST 2022
     */
    public void setEmpId(Integer empId) {
        this.empId = empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_mybatis_employee.emp_name
     *
     * @return the value of ssm_mybatis_employee.emp_name
     *
     * @mbg.generated Thu Jul 07 16:58:50 CST 2022
     */
    public String getEmpName() {
        return empName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_mybatis_employee.emp_name
     *
     * @param empName the value for ssm_mybatis_employee.emp_name
     *
     * @mbg.generated Thu Jul 07 16:58:50 CST 2022
     */
    public void setEmpName(String empName) {
        this.empName = empName == null ? null : empName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_mybatis_employee.emp_age
     *
     * @return the value of ssm_mybatis_employee.emp_age
     *
     * @mbg.generated Thu Jul 07 16:58:50 CST 2022
     */
    public Integer getEmpAge() {
        return empAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_mybatis_employee.emp_age
     *
     * @param empAge the value for ssm_mybatis_employee.emp_age
     *
     * @mbg.generated Thu Jul 07 16:58:50 CST 2022
     */
    public void setEmpAge(Integer empAge) {
        this.empAge = empAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_mybatis_employee.emp_sex
     *
     * @return the value of ssm_mybatis_employee.emp_sex
     *
     * @mbg.generated Thu Jul 07 16:58:50 CST 2022
     */
    public String getEmpSex() {
        return empSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_mybatis_employee.emp_sex
     *
     * @param empSex the value for ssm_mybatis_employee.emp_sex
     *
     * @mbg.generated Thu Jul 07 16:58:50 CST 2022
     */
    public void setEmpSex(String empSex) {
        this.empSex = empSex == null ? null : empSex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_mybatis_employee.emp_email
     *
     * @return the value of ssm_mybatis_employee.emp_email
     *
     * @mbg.generated Thu Jul 07 16:58:50 CST 2022
     */
    public String getEmpEmail() {
        return empEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_mybatis_employee.emp_email
     *
     * @param empEmail the value for ssm_mybatis_employee.emp_email
     *
     * @mbg.generated Thu Jul 07 16:58:50 CST 2022
     */
    public void setEmpEmail(String empEmail) {
        this.empEmail = empEmail == null ? null : empEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_mybatis_employee.d_id
     *
     * @return the value of ssm_mybatis_employee.d_id
     *
     * @mbg.generated Thu Jul 07 16:58:50 CST 2022
     */
    public Integer getdId() {
        return dId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_mybatis_employee.d_id
     *
     * @param dId the value for ssm_mybatis_employee.d_id
     *
     * @mbg.generated Thu Jul 07 16:58:50 CST 2022
     */
    public void setdId(Integer dId) {
        this.dId = dId;
    }
}